name: Strong
main: com.strixmc.strong.bukkit.Strong
version: 1.1.0
author: Sainted
api-version: 1.13

permissions:
  strong.bypass.cooldown:
    description: Permission to bypass streaming command cooldown.
    default: false